services:
  db:
    image: postgres:15-alpine
    container_name: pokeapi_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pokeapi_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      POKEAPI_URL: ${POKEAPI_URL}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pokeapi_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      # Use localhost as this is executed in client's browser, targeting the host's exposed port 3000
      VITE_API_URL: ${VITE_API_URL}

volumes:
  pgdata:
